version: '3.5'

networks:
  test-net:

services:
  postgres:
    image: postgres
    container_name: pgtest
    networks:
      - test-net
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
  flask:
    build: ./flask
    container_name: pytest
    networks:
      - test-net
    ports:
      - "5000:5000"
